server {
    listen 80;
    server_name test.nutrikris.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name test.nutrikris.ru;

    ssl_certificate /etc/letsencrypt/live/app.nutrikris.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.nutrikris.ru/privkey.pem;

    root /var/www/vforme_test/frontend/dist;
    index index.html;

    location /api/ {
        proxy_pass http://localhost:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
        alias /var/www/vforme_test/admin/dist/;
        try_files $uri $uri/ /admin/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
